### PR TITLE
fix: improve wording

### PR DESCRIPTION
**Pull request by ZuBB**

### CODE REVIEW

**Comment by noveogroup-amorgunov** [comment]
@ZuBB Thx for fix

**Comment by ZuBB** [comment]
@noveogroup-amorgunov you welcome.

I was able to use your lib for project with quite strict/weird env, so I wanna thank you for lib with no deps, plain and good API and typings. Although have couple minor notices
* there some bits of babel in repo however seems it is not used. getting rid of them might speed up an install process
* target in tsconfig is es5 which is great, however in source code `array.includes()` and `object.entries() methods are used which are from es6. maybe this need to be aligned. or mention this in readme. or leave it as is
* seems like `/dist` could not be checked in, but still pushed to npm. but that need to be double checked, since I use that part of npm for a long time

**Comment by noveogroup-amorgunov** [comment]
@ZuBB thank u for cases:

- If you mean webpack module wrapper (https://github.com/noveogroup-amorgunov/localizify/blob/master/dist/localizify.js#L1-L99) it's a default webpack wrappers and I don't know how fix it. Do you have any idea?
- Good catch, typescript don't provide polyfills for this one. I will try to fix it soon
- I publish new version using https://github.com/sindresorhus/np. What kind of checking do you expect?

**Comment by ZuBB** [comment]
Hi @noveogroup-amorgunov 

> If you mean webpack module wrapper (https://github.com/noveogroup-amorgunov/localizify/blob/master/dist/localizify.js#L1-L99) it's a default webpack wrappers and I don't know how fix it. Do you have any idea?

no, I meant next
* https://github.com/noveogroup-amorgunov/localizify/blob/master/.babelrc
* https://github.com/noveogroup-amorgunov/localizify/blob/master/package.json#L33-L35
* https://github.com/noveogroup-amorgunov/localizify/blob/master/package.json#L40

my guess is that they can be removed as you do ts to js compilation with help of ts-loader

> Good catch, typescript don't provide polyfills for this one. I will try to fix it soon

I do not know what is best solution here. In my case I ought to take care about polyfill myself (again weird env). plain inclusion of corejs or any other alternative will not work for me. probably some note in readme would be enough for now.

> I publish new version using https://github.com/sindresorhus/np. What kind of checking do you expect?

I had a thought on this one and came to conclusion that there might be cases when end user needs that dir. I would recommend ignore my initial idea on this. keep it as is

**Comment by noveogroup-amorgunov** [comment]
hey @ZuBB 

> my guess is that they can be removed as you do ts to js compilation with help of ts-loader

I think you are right, babel is not required. But now build process takes just 3 seconds, so it's a not a problem. But I will fix someday

> I do not know what is best solution here. In my case I ought to take care about polyfill myself (again weird env). plain inclusion of corejs or any other alternative will not work for me. probably some note in readme would be enough for now.

I prepare pull request, where change Object.entries -> Object.keys and Array.includes to Array.indexOf: https://github.com/noveogroup-amorgunov/localizify/pull/6 It should fix a problem.

> I had a thought on this one and came to conclusion that there might be cases when end user needs that dir. I would recommend ignore my initial idea on this. keep it as is

👍

**Comment by ZuBB** [comment]
> now build process takes just 3 seconds

its not about build time. its about install time. I suggest to remove 3 deps from package.json that are not used

**Comment by noveogroup-amorgunov** [comment]
These dependencies are installed as devDependencies, so if a user uses the library as npm dependency, it doesn't matter. But for development it matters, I agree with u and will fix it

**Pull request merged**
